Fixes tensorize bug and clarifies args
aguirre-lab/ml4c3 pull request #1078
Opened 2020-12-30 17:16 UTC by RogerPallares

## Issues closed
Closes #1053
Closes #947 

## Changelog
- [x] Fixes bug in tensorization. Only desired patients are tensorized again.
- [x] Changes arguments for tensorization as they refer to adt mrns and not adt indices.

## Checklist
- [x] The following are complete:
    - Added or revised tests if appropriate.
    - If new packages are installed, `requirements.txt` is updated.
    - If documentation should be updated, a new issue was made in `ml4c3-wiki`.
    - The PR name describes its content and does not contain "Ref #".
    - The PR does not add PHI.

2020-12-31 03:57 UTC, erikr requested changes
Great work Roger!

Some minor questions below.

Also, I can't comment on this for some reason, but can we delete this commented code in `/ingest/icu/tensorizer.py`?

![Screen Shot 2020-12-30 at 10 56 41 PM](https://user-images.githubusercontent.com/1253422/103393733-4976de00-4af2-11eb-9e3d-8e5f628a3e2c.png)

Thanks.

2020-12-31 03:57 UTC, erikr commented on ml4c3/arguments.py
> +        "--adt_start_mrn",
Earlier I suggested we change this arg name to show the value refers to MRNs.

However, I realized these args refer to indices in the table of MRNs, not the start and end MRN itself.

What name makes sense to you?

2020-12-31 03:57 UTC, erikr commented on ml4c3/arguments.py
> +        type=int,
If you set the default to `0`, is `type=int` inferred and thus unnecessary here?

2020-12-31 04:25 UTC, erikr commented
Branch seems to work. I am using the syntax in the body of https://github.com/aguirre-lab/ml4c3/issues/761 (which I just updated) and it is running smoothly.

2020-12-31 13:11 UTC, RogerPallares commented on ml4c3/arguments.py
> +        type=int,
Yes, I'm pretty sure it is already inferred. However, including the type remarks that it's an `int` and not a `float`, in this case, avoiding any confusion someone could have. I guess from a practical point of view we don't need the `type=int`. I don't mind removing it. Here they have an interesting discussion about that:
https://stackoverflow.com/questions/64498806/what-is-the-inferred-type-of-a-function-argument-with-a-default-value-but-no-typ

2020-12-31 13:31 UTC, RogerPallares commented on ml4c3/arguments.py
> +        "--adt_start_mrn",
Okay, actually I did this solution to create the PR but I would like some input here. First and most important, these arguments are shared in both `edw` pipeline and `tensorize` pipeline. The initial name `adt_start_index` and `adt_end_index` makes sense in the `edw` pipeline as it is the start/end row (index) in `adt` table that the user takes when pulling EDW data. However, in the `tensorize` pipeline these arguments take the first and the last patient (`mrn`) in the `adt`, therefore not following the index, and so names don't reflect properly what the arguments really do.

The solution I did here, which I don't think is the best, is to duplicate the arguments: now we have both `adt_start_index` and `adt_end_index` for `edw` pipeline and `adt_start_mrn` and `adt_end_mrn` for `tensorize` pipeline. However, I think it would be much better if we had only 2 arguments that could be shared in both pipelines. What do you think? 
If we want to have only 2 arguments then we need to find a name that is suitable for both cases, or adapt the code in some way that the argument name makes sense. If we are ok on duplicating arguments, then we can think of a good name for the `tensorize` pipeline. It is true that `adt_start_mrn` creates confusion because it seems that we need to include an mrn and not an index. I also thought of `adt_mrn_start_index`, but it's a little bit long, how about `mrn_start_index`?

2020-12-31 13:47 UTC, erikr commented
Multiprocessing is not working as intended for me.

I tensorize using syntax in https://github.com/aguirre-lab/ml4c3/issues/761#issue-738302638.

I expect to see all cores utilized, but I only see one being used near 100%:
![Screen Shot 2020-12-31 at 8 46 36 AM](https://user-images.githubusercontent.com/1253422/103412758-b1eeab00-4b44-11eb-9e1e-47cfb3f25e1a.png)

The code (in your branch) looks correct, and I did not set `--num_workers` to 1 (so by default it should use all cores):
https://github.com/aguirre-lab/ml4c3/blob/dfb50064dddbcae793c3c392fea218acb67ed3de/ingest/icu/tensorizer.py#L124-L131

2020-12-31 13:54 UTC, erikr commented on ml4c3/arguments.py
> +        type=int,
If I remove the `type=int` from these arguments, and call the pipeline using floats:
```
./scripts/run.sh $PWD/ml4c3/recipes.py tensorize_icu_no_edw_pull  \
--num_workers 4 \
--adt /media/ml4c3/cohorts_lists/adt_cabg.csv \
--xref /media/ml4c3/cohorts_lists/xref_cabg.csv \
--alarms /media/ml4c3/bedmaster_alarms \
--adt_start_mrn 1001.5 \
--adt_end_mrn 1200.2 \
--tensors ~/icu-final-2 \
--staging_dir ~/icu-temp-2 \
--staging_batch_size 10 \
--allow_one_source \
--overwrite
```

I get the following error:
```
2020-12-31 08:51:54 - ERROR - recipes:89 - 'str' object cannot be interpreted as an integer
Traceback (most recent call last):
  File "/home/erikr/ml4c3/ml4c3/recipes.py", line 63, in run
    tensorize_icu(args)
  File "/usr/local/lib/python3.8/dist-packages/ingest/icu/tensorizer.py", line 367, in tensorize
    patients = range(args.adt_start_mrn, args.adt_end_mrn, args.staging_batch_size)
TypeError: 'str' object cannot be interpreted as an integer
```

Changing the input values to what should be ints also fails:
```
--adt_start_mrn 1001 \
--adt_end_mrn 1200 \
```
because the values are based as strings.

So it seems explicitly setting the type as `int` is required.

2020-12-31 13:56 UTC, erikr commented on ml4c3/arguments.py
> +        "--adt_start_mrn",
Can we change the `tensorize` pipeline to operate using the indices of the `adt` table, instead of the actual MRN values?

`tensorize` requires an ADT table containing MRNs, so this seems possible.

This would make `adt_start_index` and `adt_end_index` applicable to both `edw` and `tensorize` pipelines, and remove the need for another set of arguments `adt_start_mrn` and `adt_end_mrn`.

2020-12-31 16:26 UTC, RogerPallares commented
I tensorized either with `num_workers 5` and without setting the argument (thus using all cpus) and works fine for me. Could it be that when you woke up the process was tensorizing the last patient? Think that if the last patient has a lot of CSNs, it will take some time to tensorize it. If you run the process now for 10 patients and you check cpu usage, is it still only using one? (wait for the pipeline to copy all files and check when it starts tensorizing.)

2020-12-31 18:02 UTC, erikr commented
Ah, I see the issue. If you set
```
--num_workers 30 \
--staging_batch_size 10 \
```

the pipeline tensorizes 10 patients at a time and use 10 workers.

2021-01-01 00:02 UTC, erikr commented on ml4c3/arguments.py
> +        "--adt_start_mrn",
@aguirre-lab/ml4c3-dev What do others think? Would be great to get some input here.

2021-01-01 15:47 UTC, erikr commented on ml4c3/arguments.py
> +        "--adt_start_mrn",
If the user does not set `--adt_start_mrn` and `--adt_end_mrn`, the following error is thrown at line 370 in `tensorizer.py`:

```
TypeError: 'NoneType' object cannot be interpreted as an integer
```

because `range` needs non-`None` type inputs.

2021-01-01 16:07 UTC, erikr commented
> The initial name `adt_start_index` and `adt_end_index` makes sense in the edw pipeline as it is the start/end row (index) in adt table that the user takes when pulling EDW data.

Is this table correct?
```
| adt_index | patient_index | mrn  | csn  |
|-----------|---------------|------|------|
| 0         | 0             | 1234 | 8285 |
| 1         | 0             | 1234 | 9291 |
| 2         | 1             | 5232 | 9192 |
```

In the EDW ingest pipeline, we iterate over rows of the table above, e.g. `mrn, csn` pairs.

In the ICU tensorization pipeline, we iterate over patient MRNs.

2021-01-01 16:58 UTC, erikr commented on ml4c3/arguments.py
> +        "--adt_start_mrn",
I am opening a PR to your branch that resolves this.

2021-01-02 10:57 UTC, RogerPallares commented on ml4c3/arguments.py
> +        "--adt_start_mrn",
Thanks for finding this out!

2021-01-02 11:02 UTC, RogerPallares commented
> Ah, I see the issue. If you set
> 
> ```
> --num_workers 30 \
> --staging_batch_size 10 \
> ```
> 
> the pipeline tensorizes 10 patients at a time and use 10 workers.
> 
> Is that correct? Is that desired?

Yes that is correct, if we set the batch size to 10, we are only tensorizing 10 patients in our local workstations, so even if we have 30 workers, only 10 patients simultaneously will be tensorized. The approach though, is to have a batch size larger, about 100 patients, then the number of patients tensorized at a time is constrained by the number of workers defined by the user. Also, keep in mind that we implemented a limit for the number of workers, if a number of workers higher than the number of cpu's is set, the code will automatically reduce the number of workers to the same number of cpu's.

2021-01-02 11:04 UTC, RogerPallares commented
> > The initial name `adt_start_index` and `adt_end_index` makes sense in the edw pipeline as it is the start/end row (index) in adt table that the user takes when pulling EDW data.
> 
> Is this table correct?
> 
> ```
> | adt_index | patient_index | mrn  | csn  |
> |-----------|---------------|------|------|
> | 0         | 0             | 1234 | 8285 |
> | 1         | 0             | 1234 | 9291 |
> | 2         | 1             | 5232 | 9192 |
> ```

Yes this table is correct!

2021-01-02 16:50 UTC, erikr approved these changes

2021-01-02 16:52 UTC, merged