Secure visualizer app with authentification
aguirre-lab/ml4c3 pull request #1104
Opened 2021-01-02 18:34 UTC by epalto

## Issues closed
Closes #1073 

## Changelog
- [x] Shell prints a token to authenticate users when using the visualizer

## Checklist
- [x] The following are complete:
    - Added or revised tests if appropriate.
    - If new packages are installed, `requirements.txt` is updated.
    - If documentation should be updated, a new issue was made in `ml4c3-wiki`.
    - The PR name describes its content and does not contain "Ref #".
    - The PR does not add PHI.

2021-01-05 00:12 UTC, erikr commented
Aaron said the web app should only be run locally.

Eric,
1. Does this change interrupt your or anyone else's workflow?
2. Is the change be difficult to make? I think it would involve removing some code and actually simplify the recipe.

Also, did you find how to push the updated Docker images to ghcr.io?

2021-01-05 12:02 UTC, erikr commented
Tests fail on `master`. Will investigate.

2021-01-05 12:37 UTC, epalto commented
Thanks Erik! This PR has the changes needed to secure the visualizer locally so no further work should be done for Aaron's request. I also built and pushed the docker image but it seems that whenever the image is rebuilt, tests fail

2021-01-05 13:30 UTC, erikr requested changes
I tested the functionality on the new branch. Nice work!

Although the app is served to `0.0.0.0`, can we print the address `http://$MACHINE_NAME.partners.org:8888` so the user can more easily get to the app?

Can you remind me why `-m /media/mad3/hd5` is required when `./scripts/run.sh` mounts the entirety of `/media` by default?

2021-01-05 14:18 UTC, StevenSong commented
When Aaron says that we must run locally, what does that mean? that we shouldnt be able to access it from e.g. everest.partners.org? Should we have it setup such that we must ssh tunnel to the machine to access it remotely or remote desktop to the machine to access it?

2021-01-05 14:24 UTC, erikr commented
The most secure solution is to not be able to access the app at `everest.partners.org` from any machine on the MGH network.

I think SSH tunneling could work. But I dislike remote desktop.

Thoughts?

2021-01-05 14:40 UTC, StevenSong commented
i see, so it must not be served to everest.partners.org - this is a more complex ask. the solutions i can think of are:
- change the firewall on everest to restrict the port to only the local machine (not even local network) - the issue with this is it is difficult to generalize through code/automation i.e. if we want to run the visualizer on olympus, we ought to modify the firewall on olympus. we ought to also restrict the port for the visualizer then
- the other solution may just be to have the webapp itself block connections from external IP addresses, which should be doable from the visualizer code - I'm not sure if this actually works with ssh tunneling but something to test

2021-01-05 15:10 UTC, StevenSong commented
https://stackoverflow.com/questions/22251038/how-to-limit-access-to-flask-for-a-single-ip-address

this SO actually has solutions to both kinds of questions

actually another possibility is to configure the firewall within our docker container via the run script to restrict access - this might be the best option (OS level restriction and portable because we use docker) but still more complex than just doing it in Flask

2021-01-05 15:50 UTC, epalto commented
Should those restrictions be applied to Jupyter Notebooks too? If so, it may be better to configurate it on docker so that it secures both things at the same time

>Can you remind me why -m /media/mad3/hd5 is required when ./scripts/run.sh mounts the entirety of /media by default?

When you launch the visualizer, this path is automatically written on the hd5_path input so that the user doesn't have to type it every time.

2021-01-05 15:58 UTC, erikr commented on visualizer/run.py
> +    random_tocken = str(uuid4())
```suggestion
    random_token = str(uuid4())
```

2021-01-05 15:58 UTC, erikr commented on visualizer/run.py
> +        {"aguirrelab": random_tocken},
```suggestion
        {"aguirrelab": random_token},
```

2021-01-05 15:58 UTC, erikr commented on visualizer/run.py
> +    \t Password: {random_tocken}
```suggestion
    \t Password: {random_token}
```

2021-01-05 16:00 UTC, erikr commented
Why the import statements inside of `run`? Why not put them at the top of the script?

2021-01-05 16:58 UTC, epalto commented
> What do you think of the following syntax?

The reason why we chose this notation is for synchronization with Docker. 
The `--port` argument is not free because the chosen port needs to be linked with the container port. By default, the container port links the port 8888 so if you run:
```
./scripts/run.sh -v \
...
--port 8010 \
...
```
the visualizer will run inside Docker on port 8010, which won't be accessible from outside the container.

The same thing happens with `--tensors`: the path is input with the `-m` option to make sure that whichever path is chosen, it gets mounted to the container. For instance, if you had data in `/data/hd5`,  the syntax ` ./scripts/run.sh -m /data/hd5 -v` would both mount that path and launch visualizer in it, while the syntax `--tensors /data/hd5` would not mount the path so the visualizer wouldn't find the files.

Anyway, this may need to be changed when once we have different paths for BM and EDW.

> Why the import statements inside of run? 

That's because some code needs to be run before importing those files. In particular, the layout can be customized with the `--options_file` so the configuration needs to be loaded before creating the layout and setting the callbacks.

2021-01-05 17:15 UTC, erikr commented
> The reason why we chose this notation is for synchronization with Docker.

I understand, thanks for explaining. Makes sense.

> The same thing happens with --tensors: the path is input with the -m option to make sure that whichever path is chosen, it gets mounted to the container. For instance, if you had data in /data/hd5, the syntax ./scripts/run.sh -m /data/hd5 -v would mount that path and launch visualizer on it, while the syntax --tensors /data/hd5 would not mount the path so the visualizer wouldn't find the files.

I believe `-m` in `run.sh` recursively mounts at that path. So when we mount via `-m /data`, Docker has access to `/data/hd5`, `/data/edw`, etc.. and `--tensors /data/any_subdirectory` works.

When we call `train` recipes, we don't mount specific subfolders. We by default mount `-m /storage/shared`, and can access and train on data in `/storage/shared/ecg`.

@StevenSong am I missing something here?

2021-01-05 17:24 UTC, epalto commented
That's right, the `-m /media/hd5/` is redundant because the `/media/` directory is mounted by default and it includes all subdirectories, but the visualizer needs the specific path where it looks for the file. It is only redundant if your data is inside the `/media` directory because this one is mounted by default, but if you want to add data from another directory, say the `/data/hd5` directory, it won't be redundant

2021-01-05 17:50 UTC, erikr commented
> ...but it's a way to specify the exact path where the .hd5 files are stored, which is needed by the visualizer

I understand, thanks for clarifying.

I propose a future improvement (out of scope for this PR though) would be to not require the user to mount the exact path in the run script via `-m`. The app would have a dropdown menu that lists every directory found at the `-m` path (identified via `os.walk`), and the user can select the parent dir containing HD5s they wish to load and visualize data from.

2021-01-06 02:00 UTC, epalto commented
Sounds good! How about we incorporate that when we add the modifications for an EDW path and a BM path (Separate EDW and Bedmaster milestone)?

2021-01-06 03:01 UTC, erikr commented
> Sounds good! How about we incorporate that when we add the modifications for an EDW path and a BM path (issue #1126)?

Great, thank you for opening that new issue. I appreciate it!

2021-01-07 15:27 UTC, erikr approved these changes

2021-01-07 15:31 UTC, erikr commented
Discussed current authentication method. We believe this is sufficiently secure. Can revisit and devise other authentication protocols in the future if necessary.

2021-01-07 15:31 UTC, merged