Consistent argument semantics in model diagram plot function calls
aguirre-lab/ml4c3 pull request #1151
Opened 2021-01-15 18:49 UTC by erikr

## Issues closed
Closes #1141

## Changelog
- [x] Function which plots condensed architecture diagram is called with specific arguments instead of entire `args` object.
- [x] File names of architecture diagram images are `architecture` and `architecture-condensed` so they are sorted adjacent to each other in the `output_folder`.
- [x] File names of other plots use `-` instead of `_`.

## Checklist
- [x] The following are complete:
    - Added or revised tests if appropriate.
    - If new packages are installed, `requirements.txt` is updated.
    - If documentation should be updated, a new issue was made in `ml4c3-wiki`.
    - The PR name describes its content and does not contain "Ref #".
    - The PR does not add PHI.

2021-01-16 17:40 UTC, erikr commented
@StevenSong when you have a chance, can you please review? Thanks!

2021-01-18 14:55 UTC, StevenSong requested changes
great cleanup, minor requests

2021-01-18 14:55 UTC, StevenSong commented on ml4c3/arguments.py
> +        type=list,
this is redundant with `nargs=4` akin to how we chose not to specify `type=bool` when `action="store_true/false"`

2021-01-18 14:55 UTC, StevenSong commented on ml4c3/arguments.py
> +        type=str,
this is redundant as argument types are strings unless otherwise specified

2021-01-18 14:55 UTC, StevenSong commented on ml4c3/arguments.py
> +        type=str,
redundant

2021-01-18 14:55 UTC, StevenSong commented on ml4c3/models.py
> +                tensor_maps_out=args.tensor_maps_out,
this is alphabetically sorted but not necessarily logically sorted,  e.g. I usually put the conv/dense/res block arguments together

style choice, fine either way

2021-01-18 14:55 UTC, StevenSong commented on ml4c3/plots.py
> -def plot_architecture_diagram(dot: pydot.Dot, image_path: str):
pydot might be an unused import now, might be okay to remove

2021-01-18 16:13 UTC, erikr commented on ml4c3/arguments.py
> +        type=str,
Although it is redundant, I like it being explicit. I was adding type hints to the function and had to refer to `arguments.py` to figure out the types. But if args are default strings, then can remove.

2021-01-18 16:14 UTC, erikr commented on ml4c3/models.py
> +                tensor_maps_out=args.tensor_maps_out,
I used to logically sort but it became significant manual effort. `:sort` in vim does this instantly, and if we consistently sort in alphabetical order, it should be easier to find args.

2021-01-18 16:26 UTC, erikr commented on ml4c3/plots.py
> -def plot_architecture_diagram(dot: pydot.Dot, image_path: str):
We initialize a `pydot.Node` later on in the function so It think we still need to import it.

However I will only import what we use: `from pydot import Node`.

2021-01-18 16:55 UTC, StevenSong commented on ml4c3/plots.py
> -def plot_architecture_diagram(dot: pydot.Dot, image_path: str):
ah good point

2021-01-18 16:59 UTC, StevenSong approved these changes

2021-01-18 17:35 UTC, merged