Hyperoptimization Refactor
aguirre-lab/ml4c3 pull request #1153
Opened 2021-01-15 22:20 UTC by StevenSong

## Issues closed
Closes #1133 

check out this dropbox folder for a run script, hyperopt config json, and all the results: https://www.dropbox.com/sh/gg76wbow7n89cul/AACKM_W6Mo_tdjD9EEbWdO4Fa?dl=0

## Changelog
- [x] hyperoptimize is now a lightweight dispatcher that 
    - loads a json hyperopt config file
    - calls a function that takes an updated args object and returns some performance metrics
- [x] provides a template for a function which spreads models across GPUs
    - use `--hyperoptimize_workers` to specify the number of models to try in parallel, this must be the same number of gpus passed to `run.sh` (see example run script in dropbox, use e.g. `-d 0,1,2` and `--hyperoptimize_workers 3`)
- [x] refactors alot of code in recipes to not import tensorflow until absolutely necessary (this causes tensorflow runtime to be configured and prevents dynamic GPU allocation hyperopt relies on)

## Checklist
- [x] The following are complete:
    - Added or revised tests if appropriate.
    - If new packages are installed, `requirements.txt` is updated.
    - If documentation should be updated, a new issue was made in `ml4c3-wiki`.
    - The PR name describes its content and does not contain "Ref #".
    - The PR does not add PHI.

2021-01-15 22:26 UTC, StevenSong commented
i think the tests are an easy fix, may address over the weekend

2021-01-16 16:05 UTC, raimonpv approved these changes
Discuss comments, nice work!

2021-01-16 16:05 UTC, raimonpv commented on ml4c3/hyperoptimizers.py
> +def train_keras_model(
should we change the name of the function as `scikit-learning` models can be trained too?

2021-01-16 17:48 UTC, erikr requested changes
Fantastic work. This will be really helpful improvement to our infra!

I appreciate the sample syntax and output you provided. Doing so should be standard workflow for PRs that modify or implement new functionality.

The syntax feels intuitive and I like the formatting of the output.

I have some questions and suggestions below.

2021-01-16 17:48 UTC, erikr commented on ml4c3/arguments.py
> +            tf.config.experimental.set_memory_growth(gpu, True)
Should the tf config be modified prior to building tensor maps? https://github.com/aguirre-lab/ml4c3/pull/1152

2021-01-16 17:48 UTC, erikr commented on ml4c3/hyperoptimizers.py
> +        os.path.join(base_output_folder, "metrics_and_hyperparameters.csv"),
Minor request, style preference:
```suggestion
        os.path.join(base_output_folder, "metrics-and-hyperparameters.csv"),
```

2021-01-16 17:48 UTC, erikr commented on ml4c3/logger.py
> +    log_console: bool = True,
I like the precise control this affords.

In `dispatch.py`, should `load_config` be called with `log_console = False`? https://github.com/aguirre-lab/ml4c3/blob/78255c344911f8ab65688ec5dc35d1efeadc2d0b/scripts/dispatch.py#L219

2021-01-16 17:48 UTC, erikr commented on ml4c3/hyperoptimizers.py
> +        from ml4c3.arguments import _load_tensor_maps
Do you import these functions after setting `os.environ` variables because these imported functions import tensorflow functions that look at `os.environ` variables, and you want each process (`train_model`) to have its own `gpu`?

2021-01-16 17:48 UTC, erikr commented on ml4c3/recipes.py
> +def build_multimodal_multitask(args: argparse.Namespace):
agreed

2021-01-16 17:48 UTC, erikr commented on ml4c3/recipes.py
> +            # Imports: first party
```suggestion
```

2021-01-16 17:48 UTC, erikr commented on ml4c3/recipes.py
>              tensorize_ecg(args)
I like the selective imports within each switch condition.

But the spacing can be improved so newlines separate recipes rather than the import and the call to the imported function:

```suggestion
        elif args.recipe == "hyperoptimize":
            from ml4c3.hyperoptimizers import hyperoptimize  # isort: skip
            hyperoptimize(args)
            
        elif args.recipe == "tensorize_ecg":
            from ingest.ecg.tensorizer import tensorize as tensorize_ecg  # isort: skip
            tensorize_ecg(args)
            
```

May need to use
```
# fmt: off

# fmt: on
```

2021-01-16 17:48 UTC, erikr commented on scripts/run.sh
> +            GPU_DEVICE="--gpus \"device=${OPTARG}\""
Why add quotes?

2021-01-18 15:40 UTC, StevenSong commented on ml4c3/hyperoptimizers.py
> +def train_keras_model(
this should probably be more nuanced, we dont need the GPUs for the sklearn models, maybe checking what the recipe is would be good for which function to use - will implement a function for hyperopt of those models

2021-01-18 16:30 UTC, StevenSong commented on ml4c3/arguments.py
> +    if "input_tensors" in args and args.recipe != "explore_icu":
good idea

2021-01-18 16:33 UTC, StevenSong commented on ml4c3/recipes.py
> +def build_multimodal_multitask(args: argparse.Namespace):
should `recipes.py` be just the switch statement? functions like `build`, `infer`, `train` do not really encode any logic - they just chain a bunch of other functions and define the entirety of the recipe - if not recipes, i'm not sure `models.py` is appropriate either

2021-01-18 16:36 UTC, StevenSong commented on ml4c3/arguments.py
> +            tf.config.experimental.set_memory_growth(gpu, True)
good catch, fixed

2021-01-18 16:42 UTC, StevenSong commented on ml4c3/logger.py
> +    log_console: bool = True,
no, dispatch launches separate shells in which each logger is separate - to prevent the output form each shell being sent back to stdout, we could set the config within each recipe call but that requires more cmd line arguments and I dont think that's worth it - in dispatch, instead I just send stdout from each shell to /dev/null

in hyperopt, we require each logger be reconfigured within each process so that each trial produces its own log file - while doing that, it was easier to disable the console output instead of doing the /dev/null hack

2021-01-18 16:45 UTC, StevenSong commented on ml4c3/hyperoptimizers.py
> +        from ml4c3.arguments import _load_tensor_maps
at this point, its probably only the *call* to _load_tensor_maps which configures the tensorflow runtime so these imports could go at the top of the file - but to avoid any future confusion, i'd vote to keep them inline just in case there's some imprecise imports in the future

2021-01-18 16:47 UTC, StevenSong commented on ml4c3/recipes.py
>              tensorize_ecg(args)
fixed

2021-01-18 16:53 UTC, StevenSong commented on scripts/run.sh
> +            GPU_DEVICE="--gpus \"device=${OPTARG}\""
so that strings like `device=1,2` are passed in their entirety to the docker config, see this issue: https://github.com/NVIDIA/nvidia-docker/issues/1026

because we're calling `docker` from within a bash script, we need 1 less level of quotes (tbh I tried single+double quotes, single quotes, and double quotes and the only thing that worked was double quotes)

2021-01-18 17:34 UTC, erikr commented on ml4c3/hyperoptimizers.py
> +        from ml4c3.arguments import _load_tensor_maps
Oh I see. Sounds good!

2021-01-18 18:09 UTC, StevenSong commented on ml4c3/recipes.py
> +def build_multimodal_multitask(args: argparse.Namespace):
can this be another issue?

2021-01-18 18:33 UTC, StevenSong commented on ml4c3/hyperoptimizers.py
> +def train_keras_model(
fixed

2021-01-18 21:53 UTC, erikr approved these changes
:fire:

2021-01-18 21:54 UTC, merged

2021-01-18 22:00 UTC, erikr commented
Is there any way to infer `hyperoptimize_workers` from the values passed to `-d`?

2021-01-18 22:03 UTC, StevenSong commented
yes actually, thats probably a better idea, will implement