Separate /ingest/icu into /tensorize/bedmaster and /tensorize/edw
aguirre-lab/ml4c3 pull request #1174
Opened 2021-01-19 22:58 UTC by raimonpv

## Issues closed
Closes #1036
Closes #1098 

## Changelog
- [x] This PR separates the content from `/ingest/icu` to two different directories: `/tensorize/bedmaster` and `/tensorize/edw`
TO DO:
- [ ] Modify tests accordingly to rely just in edw or bedmaster tensorization #1181 
- [ ] Modify `/ingest/icu/assess_coverage.py` and `pre_tensorize_explorations.py` to preserve functionality. The rest of the code is already separated. #1177  and #1178 
- [ ] Add alarms to tensorization #1180 
- [ ] General cleanup (there is still shared code between `/tensorize/bedmaster` and `/tensorize/edw`) #993 
- [ ] Once HD5 files with both edw and bedmaster data are not useful/needed, delete `/ingest/icu`

I think that we can open issues to implement the rest of the points.

## Checklist
- [ ] The following are complete:
    - Added or revised tests if appropriate.
    - If new packages are installed, `requirements.txt` is updated.
    - If documentation should be updated, a new issue was made in `ml4c3-wiki`.
    - The PR name describes its content and does not contain "Ref #".
    - The PR does not add PHI.

2021-01-20 14:19 UTC, erikr commented
Since there are several other tasks you still want to do in this PR, want to convert it to a draft?

2021-01-21 21:39 UTC, RogerPallares requested changes
Great! Just some small changes.

2021-01-21 21:39 UTC, RogerPallares commented on tensorize/edw/tensorizer.py
> +    Main class to tensorize the Bedmaster data and the EDW data.
Only EDW.

2021-01-21 21:39 UTC, RogerPallares commented on tensorize/bedmaster/tensorizer.py
> +    Main class to tensorize the Bedmaster data and the EDW data.
Only Bedmaster.

2021-01-21 21:39 UTC, RogerPallares commented on tensorize/bedmaster/readers.py
> +class Reader(ABC):
Should we have this class in `./tensorize` and share it with both Bedmaster and EDW?

2021-01-21 21:39 UTC, RogerPallares commented on tensorize/bedmaster/data_objects.py
> +class ICUDataObject(ABC):
Should we have this class in `./tensorize` and share it with both Bedmaster and EDW?

2021-01-21 21:39 UTC, RogerPallares commented on tensorize/edw/readers.py
> +class Reader(ABC):
Should we have this class in `./tensorize` and share it with both Bedmaster and EDW?

2021-01-21 21:39 UTC, RogerPallares commented on tensorize/edw/data_objects.py
> +class ICUDataObject(ABC):
Should we have this class in `./tensorize` and share it with both Bedmaster and EDW?

2021-01-21 23:36 UTC, raimonpv commented on tensorize/bedmaster/readers.py
> +class Reader(ABC):
Definitely, there is an issue to make some cleanup as there is some shared code between both tensorizations #993

2021-01-22 14:28 UTC, StevenSong commented
@erikr we ought to move ecg tensorization too

also is the idea behind the separation that ingest pulls raw data and tensorization formats

2021-01-22 15:48 UTC, RogerPallares approved these changes

2021-01-22 20:12 UTC, merged