bedmaster file indexer
aguirre-lab/ml4c3 pull request #1278
Opened 2021-01-29 22:21 UTC by StevenSong

## Issues closed
Enables #1265 

## Changelog
- [x] creates an indexer that trawls through the bedmaster `.mat` files and saves the file path, the edit time, the department, the room, and most importantly, **the start and end time of signals within the specific `.mat` file**
- [x] the index itself is a postgres db running on mithril - any of our workstations can connect to it though so the indexer is currently running on everest

## Checklist
- [x] The following are complete:
    - Added or revised tests if appropriate.
    - If new packages are installed, `requirements.txt` is updated.
    - If documentation should be updated, a new issue was made in `ml4c3-wiki`.
    - The PR name describes its content and does not contain "Ref #".
    - The PR does not add PHI.

2021-01-29 23:32 UTC, erikr commented
After it finishes the first pass, we can quantify the problem and update CDAC folks.

2021-02-01 18:52 UTC, RogerPallares commented on scripts/index_bedmaster.py
> +    # List all files in the bedmaster directory, retrieving the file edit timestamp,
File edit timestamp you mean the unix timestamp that appears in bedmaster filenames?

2021-02-01 20:17 UTC, StevenSong commented on scripts/index_bedmaster.py
> +        "PASSWORD=aguirrelab;",
actually our repo is public - I'm going to change these to be command line arguments and just remove them from the code

I don't think it's really worth deleting these from our git history as connection to the worktstations requires being on the network anyways

2021-02-01 20:24 UTC, StevenSong commented on scripts/index_bedmaster.py
> +    # List all files in the bedmaster directory, retrieving the file edit timestamp,
no this retrieves the datetime that the file was created - for indexing, this helps us determine if the existing entry for a file is stale or not e.g. if we indexed the file a week ago but within the last week, it's been overwritten, we'll reindex it

2021-02-01 22:13 UTC, raimonpv requested changes
I just noted that the full path is saved. I think that it will be better to just save the last part and then merge it with the bedmaster path argument so each user can have the lm4 server mounted wherever they want

2021-02-01 22:14 UTC, RogerPallares commented on scripts/index_bedmaster.py
> +    # List all files in the bedmaster directory, retrieving the file edit timestamp,
Understood! thanks for the explanation

2021-02-01 22:20 UTC, raimonpv commented
Also if we can rename the columns by: "Path", "DepartmentDSC",  "BedLabelNM", "StartTime" and "EndTime" it will be great to keep the same styling with the column names of the different tables (ADT, xref)

2021-02-01 22:23 UTC, RogerPallares approved these changes

2021-02-01 22:23 UTC, RogerPallares commented on scripts/index_bedmaster.py
> +            f"('{fpath}', '{t_edit}', '{dept}', '{bed}', '{t_start}', '{t_end}')"
I would put as columns the same name as we have on the ADT and xref tables: fpath -> Path, dept -> DepartmentDSC, bed -> RoomBedNM (I think the others are new, otherwise I would put the same column name)

2021-02-01 22:24 UTC, RogerPallares commented
Great work! Just that rename of columns.

2021-02-02 22:18 UTC, StevenSong commented on scripts/index_bedmaster.py
> +            f"('{fpath}', '{t_edit}', '{dept}', '{bed}', '{t_start}', '{t_end}')"
done

2021-02-02 22:18 UTC, StevenSong commented
columns renamed, paths are now relative to the bedmaster folder, csv updated

2021-02-03 04:13 UTC, raimonpv approved these changes
great work!

2021-02-03 12:10 UTC, merged