Update ICU tests and upload alarms in independent bedmaster tensorization
aguirre-lab/ml4c3 pull request #1287
Opened 2021-02-01 21:46 UTC by raimonpv

## Issues closed
Closes #1232 
Closes #1177 

## Changelog
- [x] Tensorize alarms via independent bedmaster tensorization pipeline
- [x] Remove `assess_coverage` related files
- [x] Some tensorization tests relies now only on the independent tensorization

## Checklist
- [x] The following are complete:
    - Added or revised tests if appropriate.
    - If new packages are installed, `requirements.txt` is updated.
    - If documentation should be updated, a new issue was made in `ml4c3-wiki`.
    - The PR name describes its content and does not contain "Ref #".
    - The PR does not add PHI.

2021-02-02 22:21 UTC, RogerPallares requested changes
Great! Some suggestions.

2021-02-02 22:21 UTC, RogerPallares commented on tensorize/bedmaster/readers.py
> +        :return: <List[str]>  List with all the registered Bedmaster alarms
Final dot.

2021-02-02 22:21 UTC, RogerPallares commented on tensorize/bedmaster/readers.py
> +        ]
Don't we need that implementation we did some time ago that if movements table doesn't exist, it checks transfer times from ADT?

2021-02-02 22:32 UTC, RogerPallares commented
Clarify me something, for the issue related to `assess_coverage.py` script, how did you make it functional to both EDW and Bedmaster? Because in the PR I only see that you deleted the main script (probably I'm missing something).

2021-02-03 15:22 UTC, raimonpv commented on tensorize/bedmaster/readers.py
> +        Iinit Bedmaster Alarms Reader.
```suggestion
        Init Bedmaster Alarms Reader.
```

2021-02-03 15:22 UTC, raimonpv commented on tensorize/bedmaster/data_objects.py
> +        :param level: <int> Alarm Level
```suggestion
        :param level: <int> Alarm Level.
```

2021-02-03 15:22 UTC, raimonpv commented on tensorize/bedmaster/readers.py
> +        :return: <List[str]>  List with all the registered Bedmaster alarms
```suggestion
        :return: <List[str]>  List with all the registered Bedmaster alarms.
```

2021-02-03 15:24 UTC, raimonpv commented on tensorize/bedmaster/readers.py
> +        ]
This functionality is kept in the tensorization of both bedmaster and edw data. But I removed from the bedmaster tensorization as it can just rely on bedmaster data.

2021-02-03 15:25 UTC, raimonpv commented
@RogerPallares In the discussion of the issue #1177 we decided that there is no need to have this script anymore so we can proceed to delete all the related information.

2021-02-03 15:56 UTC, RogerPallares approved these changes

2021-02-03 15:58 UTC, merged