Update matching algorithm to use bedmaste_index file
aguirre-lab/ml4c3 pull request #1288
Opened 2021-02-01 23:04 UTC by raimonpv

## Issues closed
First step for #1265 

## Changelog
- [x] This PR modifies the matching algorithm to use the bedmaster_index table instead of just the bedmaster files name
- [ ] todo: If the change sounds reasonable, I'll modify anyplace where the matching algorithm is used and the tests

## Checklist
- [ ] The following are complete:
    - Added or revised tests if appropriate.
    - If new packages are installed, `requirements.txt` is updated.
    - If documentation should be updated, a new issue was made in `ml4c3-wiki`.
    - The PR name describes its content and does not contain "Ref #".
    - The PR does not add PHI.

2021-02-01 23:06 UTC, raimonpv commented
@StevenSong whenever you can, take a look so I can proceed with further changes

2021-02-02 02:03 UTC, StevenSong commented on tensorize/bedmaster/match_patient_bedmaster.py
> +            )
Could you explain these conditions? This seems like the crux of the change

2021-02-02 02:06 UTC, StevenSong commented on tensorize/bedmaster/match_patient_bedmaster.py
> +            )
This gives 2 options:
- `.mat` file starts an hour or more before the patient transfers to the bed and before the patient transfers out
- `.mat` file starts an hour or more after the patient transfers to the bed and ends an hour or more before the patient transfer to the bed?

2021-02-02 04:06 UTC, raimonpv commented on tensorize/bedmaster/match_patient_bedmaster.py
> +            )
So the first condition was already there, and basically will select files where the starting time is between the the transfer in and transfer out of the patient. The second condition, which is the one I've added, will take any patient which transfer in is in between the start and ending time of the bedmaster file.  So I think that it covers all the possible options.

About the 1 hour before transfer in was made by Roger and I think that the idea was to add some margin error, in case that for some reason the machines were turned on some time before the patient was transferred in. Looking again into the conditions, I think that in line 111 doesn't make sense to add this margin error.

2021-02-02 14:27 UTC, StevenSong commented on tensorize/bedmaster/match_patient_bedmaster.py
> +            )
Ah I see, okay thanks for clarifying, the conditions make sense to me now

Some follow ups:
- agreed the 1 hour margin doesnt seem necessary anymore
- should line 108 also be <=?
- we should add tests which test:
  1. `.mat` file overhangs a patient stay on the right
  2. `.mat` file overhangs a patient stay on the left
  3. `.mat` file is completely within a patient's stay
  4. a patient's stay is completely within a `.mat` file

do those conditions make sense?

2021-02-02 15:58 UTC, raimonpv commented on tensorize/bedmaster/match_patient_bedmaster.py
> +            )
agreed on what you said, I'll work on that today

2021-02-02 23:41 UTC, raimonpv commented
Done all the necessary changes to make the pipeline work with this new approach. Still need to modify and fix tests. But the changes in the pipeline are ready to review.

2021-02-03 03:59 UTC, RidwanAlam commented on tensorize/bedmaster/match_patient_bedmaster.py
> +            )
About the 1-hour margin:
even if the machine was turned on, do we rely on the data before the official `TransferIn` from the ADT ground truth?
I would rather start the capture `15 minutes` AFTER the `TransferIn` time not BEFORE.

2021-02-03 05:48 UTC, RidwanAlam requested changes
Looks good, @raimonpv. Thanks for doing this.

2021-02-03 05:48 UTC, RidwanAlam commented on tensorize/bedmaster/match_patient_bedmaster.py
> +            )
my 2 cents: the conditions are too restrictive and will have some problem as we discussed in #1258  
what about just this: 
```
xref_df = xref_df [
            (  xref_df["StartTime"].astype(float)    <=    xref_df["TransferOutDTS"]   )
            &
            (  xref_df["EndTime"].astype(float)      >=    xref_df["TransferInDTS"]     )
]
```
Btw, where are you addressing the timezone/UTC difference?

2021-02-03 14:41 UTC, raimonpv commented on tensorize/bedmaster/match_patient_bedmaster.py
> +            )
Oh after Stevens follow up points the conditions should be alright, but I like how you coded the conditions, it's simpler and clearer, although I am pretty sure that the result is the same. The format time difference is addressed in lines 79, 80 where the timezone data from the adt is converted to utc.

2021-02-03 15:24 UTC, RogerPallares commented on tensorize/bedmaster/match_patient_bedmaster.py
> +            )
Just clarifying that the one hour margin should be kept, at least to compare initial times, last bedmaster files I studied they started more or less 1 hour before the patient arrived to the room, if this margin is not added we can lose matches. Even I was thinking to enlarge it to 1 hour and a half.

2021-02-03 15:28 UTC, raimonpv commented on tensorize/bedmaster/match_patient_bedmaster.py
> +            )
by applying the rules that Ridwan suggested there is no need to add a margin anymore, right?

2021-02-03 15:52 UTC, RogerPallares commented on tensorize/bedmaster/match_patient_bedmaster.py
> +            )
yes, I didn't see @RidwanAlam's suggestion. It isn't needed anymore with this new conditions.

2021-02-03 15:53 UTC, RidwanAlam commented on tensorize/bedmaster/match_patient_bedmaster.py
> +            )
Thanks. For example, if `StartTime` is `10:00:00 am` and `TransferIn` at `12:00:00 pm`, (both `EndTime` and `TransferOut` the following day), we still want that file, right? `3600` constraint will block that.

2021-02-03 18:10 UTC, raimonpv commented
I will open a new PR as it contains changes from previous ones.

2021-02-03 18:10 UTC, closed without merging