Rpv cross reference index
aguirre-lab/ml4c3 pull request #1293
Opened 2021-02-03 18:10 UTC by raimonpv

## Issues closed
First step for #1265 

## Changelog
- [x] This PR modifies the matching algorithm to use the bedmaster_index table instead of just the bedmaster files name
- [x] Removes duplicated code in data_objects.py

## Checklist
- [x] The following are complete:
    - Added or revised tests if appropriate.
    - If new packages are installed, `requirements.txt` is updated.
    - If documentation should be updated, a new issue was made in `ml4c3-wiki`.
    - The PR name describes its content and does not contain "Ref #".
    - The PR does not add PHI.

2021-02-03 18:44 UTC, StevenSong commented
An ask, can we generate the xref table using this new algorithm and compare it to the old table? That will very quickly quantify how big the issue in #1258 is

2021-02-04 03:34 UTC, RidwanAlam approved these changes
Looks good. Thanks @raimonpv

2021-02-04 05:15 UTC, RidwanAlam commented
> An ask, can we generate the xref table using this new algorithm and compare it to the old table? That will very quickly quantify how big the issue in #1258 is

I did somewhat like that for the covid cohort:
there are 371 patients in the cohort;
old xref had 338 patients, 380 CSNs;
new xref (using bedmaster_index.csv) has 369 patients, 433 CSNs. 
~10% of the cohort-size. 
@RogerPallares @epalto @raimonpv

2021-02-04 13:40 UTC, erikr commented
> old xref had 338 patients, 380 CSNs;
> new xref (using bedmaster_index.csv) has 369 patients, 420 CSNs.

Nice work! I wish it was 1% but 10% seems like we should fix it before any downstream analyses.

I wonder if COVID cohort has a higher-than-average prevalence of `.mat` files with >1 patient, because of the chaos of the early days of the pandemic (lots of patient movement, transfers, or inaccurate ADT entries).

So are next steps to re-tensorize?
1. CABG
2. Arrest
3. COVID

Also, you can tag @aguirre-lab/ml4c3-dev to notify all core dev members of the team.

2021-02-04 13:45 UTC, erikr commented on ml4c3/arguments.py
> +    )
Can you add the default path? Since the CSV is on `mad3`, its path should be the same for all machines.

2021-02-04 13:58 UTC, raimonpv commented
>  old xref had 338 patients, 380 CSNs;

Have you computed this xref table now too? as it is a cohort that is being updated every day. To make a fair analysis you should compute the xref table using the two methods at the same time and then compare number of MRNs/CSNs but also number of files cross-referenced and number of files repeated.

> @raimonpv, what else needs to happen to resolve #1265?

Two things come to my mind:
1. Modify Bedmaster writer so just signals between transfer in and transfer out are written.
2. I think that I should modify this PR so it also adds a flag (0,1,2,3) according to the type of overlap:
    - .mat file overhangs a patient stay on the right
    - .mat file overhangs a patient stay on the left
    - .mat file is completely within a patient's stay
    - a patient's stay is completely within a .mat file

Step 2. will make step 1 computationally less expensive so we will already know if we have to check the transfer in, the transfer out, both or none. And also will help to quantify the problem.

2021-02-04 14:22 UTC, RidwanAlam commented
> > old xref had 338 patients, 380 CSNs;
> 
> Have you computed this xref table now too? as it is a cohort that is being updated every day. To make a fair analysis you should compute the xref table using the two methods at the same time and then compare number of MRNs/CSNs but also number of files cross-referenced and number of files repeated.
> 
The `xref_old` was generated within last 2 weeks. Moreover, the cohort MRNs are fixed, that's the same from September `covid-registry`, so no additional MRNs are looked for.

2021-02-04 14:22 UTC, StevenSong requested changes
a few questions and also are all the test cases of possible `.mat` and patient stay overlap accounted for?

2021-02-04 14:22 UTC, StevenSong commented on ingest/icu/readers.py
> +                raise ValueError()
more verbose error message?

2021-02-04 14:22 UTC, StevenSong commented on ingest/icu/readers.py
> +            bedmaster_path = os.path.join(self.bedmaster_dir, row["Path"])
are these equivalent? wouldn't `fname` before have been just the `.mat` filename whereas now `row["Path"]` is the department folder and the `.mat` file?

2021-02-04 14:22 UTC, StevenSong commented on tensorize/bedmaster/match_patient_bedmaster.py
> +            & (xref_df["EndTime"].astype(float) >= xref_df["TransferInDTS"])
nice

2021-02-04 14:22 UTC, StevenSong commented on tensorize/bedmaster/readers.py
> +                raise ValueError()
descriptive error

2021-02-04 14:22 UTC, StevenSong commented on tensorize/bedmaster/readers.py
> +            bedmaster_path = os.path.join(self.bedmaster_dir, row["Path"])
same question as earlier about old vs new paths

2021-02-04 14:22 UTC, StevenSong commented on tests/icu_ingest/test_cross_referencer.py
> +def cross_referencer() -> Iterator[CrossReferencer]:
this type hint is probably to fix mypy or pylint error? its functionally a little different because of pytest. a user of this fixture doesnt really treat it as an iterator/generator, they simply get the reader - im fine with this type hint but this type hinting pytest has come up before https://github.com/aguirre-lab/ml4c3/issues/757

2021-02-04 14:30 UTC, StevenSong commented
> 2\. I think that I should modify this PR so it also adds a flag (0,1,2,3) according to the type of overlap:
>     
>     * .mat file overhangs a patient stay on the right
>     * .mat file overhangs a patient stay on the left
>     * .mat file is completely within a patient's stay
>     * a patient's stay is completely within a .mat file
> 
> Step 2. will make step 1 computationally less expensive so we will already know if we have to check the transfer in, the transfer out, both or none. And also will help to quantify the problem.

is the phenotypic breakdown of the `.mat` file overlap something we need to know? I would just be in favor of getting this in so that the next step can start, I'm not sure the computation of the overlap type is that expensive though, I mean it should be a couple of if's and it either happens here in the cross referencer, or it happens in the writer (the writer regardless will need to check which case it is, either by looking at the actual start/end times or just by looking at the cross referencer flag)

2021-02-04 14:38 UTC, raimonpv commented on ingest/icu/readers.py
> +            bedmaster_path = os.path.join(self.bedmaster_dir, row["Path"])
yes, but the problem was  the following:
1. the files were matched and the full path was stored. 
2. Then, these files were copied in a local folder following a different structure (without subfolders by department)
3. It is not possible to match this new path with the full path of the xref, so just the `.mat` file name is used. Also this could raise errors if someone tries to use tensorization without staging. Or has lm4 server mounted in a different folder and uses the same xref.

What I did is now that we are saving the relative paths, when staging the bedmaster files we are also copying the subfolders. So then the code here is simpler

2021-02-04 14:40 UTC, StevenSong commented on ingest/icu/readers.py
> +            bedmaster_path = os.path.join(self.bedmaster_dir, row["Path"])
awesome

2021-02-04 14:53 UTC, RidwanAlam commented on ingest/icu/readers.py
> +            bedmaster_path = os.path.join(self.bedmaster_dir, row["Path"])
nice explanation, @raimonpv

2021-02-04 14:57 UTC, RidwanAlam commented
> Nice work! I wish it was 1% but 10% seems like we should fix it before any downstream analyses.
> 
> I wonder if COVID cohort has a higher-than-average prevalence of `.mat` files with >1 patient, because of the chaos of the early days of the pandemic (lots of patient movement, transfers, or inaccurate ADT entries).
> 
@RogerPallares do you want me to look into the CABG cohort xref file?

2021-02-04 15:45 UTC, raimonpv commented
> is the phenotypic breakdown of the .mat file overlap something we need to know? I would just be in favor of getting this in so that the next step can start, I'm not sure the computation of the overlap type is that expensive though, I mean it should be a couple of if's and it either happens here in the cross referencer, or it happens in the writer (the writer regardless will need to check which case it is, either by looking at the actual start/end times or just by looking at the cross referencer flag)

I just added in case the one who is in charge of the next step needs it as it's a simple manipulation of columns. I can delete it afterward if there is no need.

2021-02-04 16:04 UTC, StevenSong approved these changes
great work @raimonpv, as I am done with interviews, I can take the next step of fixing the writer. just 1 request to add a comment for future maintainers but no need to bounce back

2021-02-04 16:04 UTC, StevenSong commented on tensorize/bedmaster/match_patient_bedmaster.py
> +        ] = "patient's stay is completely within the .mat file"
this is cool but I do think there should be a cautionary comment before this section explaining that these conditions only hold true after the conditions on lines 106-109. take for example a `.mat` file that occurs entirely after a patient's stay. using this logic, they would get `OverlapID = 2`, but the conditions before the overlap ID prevent that case. again this code and logic is fine where it is but perhaps adding a comment for future maintainers will be helpful

2021-02-04 16:33 UTC, RogerPallares commented
> @RogerPallares do you want me to look into the CABG cohort xref file?

Hey @RidwanAlam, if you have bandwidth and can analyze `xref-cabg-arrest.csv` (at `/media/ml4c3/cohorts_lists`) I would really appreciate it.

2021-02-04 16:43 UTC, merged

2021-02-09 04:11 UTC, RidwanAlam commented
> Hey @RidwanAlam, if you have bandwidth and can analyze `xref-cabg-arrest.csv` (at `/media/ml4c3/cohorts_lists`) I would really appreciate it.

there are 6843 patients in the cohort (from `ADT` table);
old xref had 4803 patients, 4886 CSNs;
new xref (using bedmaster_index.csv) has 5302 patients, 5409 CSNs.
again, **~10%** of the cohort-size.
@aguirre-lab/ml4c3-dev

2021-02-09 14:30 UTC, raimonpv commented
If we go one step further, for the cabg-arrest cohort:
In the old xref, there were already files that were matched with more than one patient (856 files of a total of 59633) leading to 119 patients with at least one bedmaster file that was matched with another patient.
In the new xref, this happens for 4117 files (of a total of 74538) and 1503 patients.

2021-02-09 14:53 UTC, RidwanAlam commented
> If we go one step further, for the cabg-arrest cohort:
> In the old xref, there were already files that were matched with more than one patient (856 files of a total of 59633) leading to 119 patients with at least one bedmaster file that was matched with another patient.
> In the new xref, this happens for 4117 files (of a total of 74538) and 1503 patients.

that emphasizes the value of #1322 , right?

2021-02-09 17:09 UTC, raimonpv commented
> that emphasizes the value of #1322 , right?
Yes