bedmaster reader splits up signals
aguirre-lab/ml4c3 pull request #1322
Opened 2021-02-05 21:50 UTC by StevenSong

## Issues closed
Closes #1265 

## Changelog
- [x] reader splits signals based on patient transfer in/out times
- [ ] some more evidence that I think it's now working in comments down below

## Checklist
- [ ] The following are complete:
    - Added or revised tests if appropriate.
    - If new packages are installed, `requirements.txt` is updated.
    - If documentation should be updated, a new issue was made in `ml4c3-wiki`.
    - The PR name describes its content and does not contain "Ref #".
    - The PR does not add PHI.

2021-02-05 21:54 UTC, StevenSong commented
the plot in orange shows the same discontinuity of the `.mat` bundle from #1258 (`LUN06_620-1586396113_7_v4.mat`), where we know the data after the jump belongs to a new patient. this is highlighted by the horizontal gray line which indicates the patient xfer out time from this room

the plot in blue shows the contents of the hd5 generated after the fix in this PR. we see that at the xfer out time, the data from the hd5 continues but it is not the same set of timestamps as that of the `.mat`
![image](https://user-images.githubusercontent.com/26208374/107092972-747bde00-67d2-11eb-813e-b5a6ee72329c.png)

2021-02-07 13:12 UTC, RidwanAlam reviewed
Thanks, again @StevenSong

2021-02-07 13:12 UTC, RidwanAlam commented on tensorize/bedmaster/readers.py
> +            if len(before_right := np.where(time <= right_t)[0]) == 0:
do we need a check for invalid timestamps here?

2021-02-07 13:14 UTC, RidwanAlam commented
@epalto your review might be more valuable here :)

2021-02-08 14:27 UTC, StevenSong commented on tensorize/bedmaster/readers.py
> +        time = self["vs_time_corrected"][signal_name]["res_vs"][:, 0]
the time array will have `-1` however all the places where we compare the time array, we consider all elements of the array and so the first (few) elements being `-1` should not affect it - looking through some more specific cases where the time vector is used, I dont think it's an issue but perhaps @epalto can double check

2021-02-08 14:31 UTC, StevenSong commented on tensorize/bedmaster/readers.py
> +            if len(before_right := np.where(time <= right_t)[0]) == 0:
if invalid means values like `-1`, no, see above

if invalid means values like `nan`, no, it logs a warning but the logic is still correct
![image](https://user-images.githubusercontent.com/26208374/107233328-7622ed00-69f0-11eb-9fcb-066d8d0fe755.png)

2021-02-08 15:13 UTC, RidwanAlam commented on tensorize/bedmaster/readers.py
> +            if len(before_right := np.where(time <= right_t)[0]) == 0:
cool!

2021-02-08 17:37 UTC, RidwanAlam approved these changes
@StevenSong please wait for @epalto 's review as well. Thanks!

2021-02-08 18:51 UTC, epalto requested changes
This looks great! Just a small remark, good job!

2021-02-08 18:51 UTC, epalto commented on tensorize/bedmaster/readers.py
> +        time = time[left_idx:right_idx]
If `right_t` is None, then `time = time[0:-1]` which will crop the last value?

2021-02-08 18:51 UTC, epalto commented on tensorize/bedmaster/readers.py
> +        sf_arr = self["wv_time_original"][channel]["SampleRate"][first_idx:last_idx, 0]
same than above; [0:-1] will crop the last value

2021-02-08 18:56 UTC, StevenSong commented on ingest/icu/tensorizer.py
> +            self._main_write(tensors, mrn, visits, ICU_SCALE_UNITS)
oh sorry this was just to test, will restore for sure

2021-02-08 18:57 UTC, StevenSong commented on tensorize/bedmaster/readers.py
> +        time = time[left_idx:right_idx]
you're right, will fix

2021-02-08 20:50 UTC, StevenSong commented
@epalto any thoughts on how this affects inter-bundle correction? I think it's good but I wanted to get your take on that as well

2021-02-09 00:14 UTC, RidwanAlam approved these changes

2021-02-09 00:23 UTC, epalto commented
> @epalto any thoughts on how this affects inter-bundle correction? I think it's good but I wanted to get your take on that as well

I also think that it shouldn't affect it

2021-02-09 00:23 UTC, epalto approved these changes

2021-02-09 17:46 UTC, merged

2021-02-09 18:02 UTC, erikr commented
Great work @aguirre-lab/ml4c3-dev 🎉 !!!