Implements AdamW optimizer and
aguirre-lab/ml4c3 pull request #1334
Opened 2021-02-09 13:05 UTC by erikr

## Issues closed
Closes #1295
Closes #1333

## Changelog
- [x] Simplifies logic of selecting `AdamW` or `RAdam` optimizer classes, as well as if a static vs cyclical learning rate is selected.
- [x] Adds [`AdamW` optimizer](https://www.fast.ai/2018/07/02/adam-weight-decay/), which in some scenarios can outperform `Adam`.
- [x] Adjusts cyclical learning rate strategy parameters; 1) at instantiation of the optimizer and the learning rate schedule object, we previously needed the training set size to estimate the step size. Instead, this value is now set from a command line argument `cyclical_step_size`, and empirically values of 4 or 8 work well. 2) the initial LR and max LR are now the `learning_rate / 10` and `learning_rate * 10` respectively to explore an LR space that spans two orders of magnitude.
- [x] `ReduceLROnPlateau` is only added to the list of callables `callbacks` if we are _not_ using a cyclical LR strategy. This solves the issue in #1333.

## Checklist
- [x] The following are complete:
    - Added or revised tests if appropriate.
    - If new packages are installed, `requirements.txt` is updated.
    - If documentation should be updated, a new issue was made in `ml4c3-wiki`.
    - The PR name describes its content and does not contain "Ref #".
    - The PR does not add PHI.

2021-02-09 19:20 UTC, StevenSong commented on ml4c3/optimizers.py
> +            return AdamW(learning_rate=lr, weight_decay=wd)
```suggestion
        if learning_rate_schedule is None:
            return AdamW(learning_rate=learning_rate, weight_decay=weight_decay)
        else:
            wd = Triangular2CyclicalLearningRate(
                initial_learning_rate=weight_decay / 10,
                maximal_learning_rate=weight_decay * 10,
                step_size=step_size,
            )
            return AdamW(
                learning_rate=rate_or_schedule, weight_decay=wd, **optimizer_kwargs
            )
```

2021-02-09 19:21 UTC, StevenSong commented on ml4c3/optimizers.py
> +            return AdamW(learning_rate=lr, weight_decay=wd)
could you try the above? so its got the same schedule for learning rate as it does for weight decay

2021-02-09 19:44 UTC, erikr commented on ml4c3/optimizers.py
> +            return AdamW(learning_rate=lr, weight_decay=wd)
Thanks, will do.

I think this is redundant though:
```
wd = _get_learning_rate_schedule(weight_decay, step_size, learning_rate_schedule)
```

since above we do https://github.com/aguirre-lab/ml4c3/blob/8c471044b384208e6d80601904911a83a42ce19c/ml4c3/optimizers.py#L24-L28

so we can just do
```
return AdamW(learning_rate= rate_or_schedule, weight_decay= rate_or_schedule)
```

2021-02-09 19:48 UTC, StevenSong commented on ml4c3/optimizers.py
> +            return AdamW(learning_rate=lr, weight_decay=wd)
no no, its specifically using the `weight_decay` as the initial value

2021-02-09 19:56 UTC, erikr commented on ml4c3/optimizers.py
> +            return AdamW(learning_rate=lr, weight_decay=wd)
Oh, I see. That was not immediately obvious to me because of the lack of named args. The following is clearer (and how I'll implement):
```python
_get_learning_rate_schedule(
    learning_rate=weight_decay,
    step_size=step_size,
    learning_rate_schedule=learning_rate_schedule,
)
```

2021-02-09 20:02 UTC, StevenSong commented on ml4c3/models.py
> +            ),
I wonder if there's also ReduceWDOnPlateau?

2021-02-09 21:13 UTC, erikr commented on ml4c3/models.py
> +            ),
I did not find anything like that.

2021-02-09 21:20 UTC, StevenSong commented on ml4c3/models.py
> +            ),
I found this https://github.com/tensorflow/addons/issues/1236, but it hasn't had movement for almost a year now

2021-02-09 21:25 UTC, StevenSong commented on ml4c3/models.py
> +            ),
Does it make sense to also have weight decay-decay? I imagine it does, which is why, when using a learning rate scheduler, we apply it to both the learning rate and weight decay. perhaps we can write some custom code and inherit from the ReduceLROnPlateau class

2021-02-09 21:42 UTC, erikr commented on ml4c3/models.py
> +            ),
That's a good idea. Would it be a callback? Do you have any bandwidth to try to implement?

2021-02-09 21:43 UTC, erikr commented
`--learning_rate_schedule triangular` with `--optimizer adamw` throws this `TypeError`:

```
2021-02-09 16:40:49 - ERROR - recipes:138 - in user code:

    /usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/training.py:806 train_function  *
        return step_function(self, iterator)
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/training.py:796 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/distribute/distribute_lib.py:1211 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/distribute/distribute_lib.py:2585 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/distribute/distribute_lib.py:2945 _call_for_each_replica
        return fn(*args, **kwargs)
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/training.py:789 run_step  **
        outputs = model.train_step(data)
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/training.py:756 train_step
        _minimize(self.distribute_strategy, tape, self.optimizer, loss,
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/training.py:2743 _minimize
        optimizer.apply_gradients(
    /usr/local/lib/python3.8/dist-packages/tensorflow_addons/optimizers/weight_decay_optimizers.py:168 apply_gradients
        return super().apply_gradients(grads_and_vars, name=name, **kwargs)
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:540 apply_gradients
        apply_state = self._prepare(var_list)
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:793 _prepare
        self._prepare_local(var_device, var_dtype, apply_state)
    /usr/local/lib/python3.8/dist-packages/tensorflow_addons/optimizers/weight_decay_optimizers.py:197 _prepare_local
        wd_t = tf.identity(self._decayed_wd(var_dtype))
    /usr/local/lib/python3.8/dist-packages/tensorflow_addons/optimizers/weight_decay_optimizers.py:204 _decayed_wd
        wd_t = tf.cast(wd_t(self.iterations), var_dtype)
    /usr/local/lib/python3.8/dist-packages/tensorflow_addons/optimizers/cyclical_learning_rate.py:94 __call__
        cycle = tf.floor(1 + step / (2 * step_size))
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/variables.py:1074 _run_op
        return tensor_oper(a.value(), *args, **kwargs)
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/math_ops.py:1140 binary_op_wrapper
        raise e
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/math_ops.py:1124 binary_op_wrapper
        return func(x, y, name=name)
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/util/dispatch.py:201 wrapper
        return target(*args, **kwargs)
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/math_ops.py:1296 truediv
        return _truediv_python3(x, y, name)
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/math_ops.py:1226 _truediv_python3
        raise TypeError("x and y must have the same dtype, got %r != %r" %

    TypeError: x and y must have the same dtype, got tf.int64 != tf.float32
Traceback (most recent call last):
  File "/home/erikr/ml4c3/ml4c3/recipes.py", line 36, in run
    train_model(args)
  File "/home/erikr/ml4c3/ml4c3/recipes.py", line 194, in train_model
    train_results = train_model_from_datasets(
  File "/usr/local/lib/python3.8/dist-packages/ml4c3/models.py", line 158, in train_model_from_datasets
    history = model.fit(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/training.py", line 1098, in fit
    tmp_logs = train_function(iterator)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/def_function.py", line 823, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/def_function.py", line 696, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py", line 2855, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py", line 3213, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/function.py", line 3065, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/func_graph.py", line 986, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/def_function.py", line 600, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/func_graph.py", line 973, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in user code:

    /usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/training.py:806 train_function  *
        return step_function(self, iterator)
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/training.py:796 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/distribute/distribute_lib.py:1211 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/distribute/distribute_lib.py:2585 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/distribute/distribute_lib.py:2945 _call_for_each_replica
        return fn(*args, **kwargs)
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/training.py:789 run_step  **
        outputs = model.train_step(data)
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/training.py:756 train_step
        _minimize(self.distribute_strategy, tape, self.optimizer, loss,
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/training.py:2743 _minimize
        optimizer.apply_gradients(
    /usr/local/lib/python3.8/dist-packages/tensorflow_addons/optimizers/weight_decay_optimizers.py:168 apply_gradients
        return super().apply_gradients(grads_and_vars, name=name, **kwargs)
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:540 apply_gradients
        apply_state = self._prepare(var_list)
    /usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:793 _prepare
        self._prepare_local(var_device, var_dtype, apply_state)
    /usr/local/lib/python3.8/dist-packages/tensorflow_addons/optimizers/weight_decay_optimizers.py:197 _prepare_local
        wd_t = tf.identity(self._decayed_wd(var_dtype))
    /usr/local/lib/python3.8/dist-packages/tensorflow_addons/optimizers/weight_decay_optimizers.py:204 _decayed_wd
        wd_t = tf.cast(wd_t(self.iterations), var_dtype)
    /usr/local/lib/python3.8/dist-packages/tensorflow_addons/optimizers/cyclical_learning [...]

2021-02-09 21:45 UTC, StevenSong commented on ml4c3/models.py
> +            ),
yes, I could try, it would be a callback and I was going to just copy over the implementation for RLRoP and add some lines for WD as well - going to copy the name suggested in that issue in TFA and call it ReduceLROnPlateauWithWeightDecay

2021-02-09 21:54 UTC, StevenSong commented
> ```
> /usr/local/lib/python3.8/dist-packages/tensorflow_addons/optimizers/cyclical_learning_rate.py:94 __call__
>         cycle = tf.floor(1 + step / (2 * step_size))
> ```

it doesnt look like its using the updated code for tfa, where it should be https://github.com/tensorflow/addons/blob/v0.12.0/tensorflow_addons/optimizers/cyclical_learning_rate.py#L94-L95

2021-02-10 01:36 UTC, erikr commented
Recap of Zoom session: needed to call 
```
./scripts/run.sh -d $GPU -i d33cf78b6597 $PWD/ml4c3/recipes.py train \
```
with the `-d` flag before `-i`.

2021-02-10 01:44 UTC, erikr commented
Giving up on LR scheduler. Happy with `AdamW`.

2021-02-10 14:05 UTC, StevenSong requested changes
2 questions, actual changes to add adamw looking great

2021-02-10 14:05 UTC, StevenSong commented on ml4c3/models.py
> +            ),
Did you want me to resolve this in this PR or a new issue?

2021-02-10 14:05 UTC, StevenSong commented on ml4c3/models.py
> -            NON_KERAS_OPTIMIZERS.values(),
could you try loading one of the adamw or radam models using our pipeline? I suspect it might need these "custom" optimizers

2021-02-10 14:52 UTC, erikr commented on ml4c3/models.py
> +            ),
Let's do a new issue https://github.com/aguirre-lab/ml4c3/issues/1347. Thanks!

2021-02-10 14:52 UTC, erikr commented on ml4c3/models.py
> -            NON_KERAS_OPTIMIZERS.values(),
I called `infer` using model weights from several of the hyperoptimize-generated experiments, inspected the `model` object that was loaded, and confirmed that both `radam` and `adamw` optimizers are in the loaded model, inference is performed, and expected output is generated.

Does not seem like we need to load these optimizers into `custom_objects`.

2021-02-10 14:53 UTC, StevenSong approved these changes
great stuff, thx for addressing

2021-02-10 14:56 UTC, merged

2021-02-10 14:56 UTC, erikr commented
Thanks for all of your help with this! TF is not as fun as I imagined.